name:                hslog
version:             0.1.0.0
github:              "Bannerets/hslog"
license:             MIT
author:              "Bannerets"
maintainer:          "comonoid@protonmail.com"
copyright:           "2019 Bannerets"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Bannerets/hslog#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- containers
- transformers

library:
  source-dirs: lib

executables:
  hslog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hslog

tests:
  hslog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hslog
    - hspec
    - hspec-megaparsec
